# Site settings
title: "The A Team"
description: "ISEE Team Project 2017"
baseurl: "https://jdvala.github.io/ProjectTF/"
url: "https://jdvala.github.io/ProjectTF/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "Home"
    url: 
  - title: "About"
    url: /about
  - title: "Blog"
    url: /_posts
  
