# Site settings
title: "The A Team"
description: "ISEE Team Project 2017"
baseurl: ""
url: "

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "Blog"
    url: /_posts
  
